name: CD (BaseMauiApp)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BaseMauiApp/**
      - .github/workflows/cd_basemauiapp**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-BaseMauiApp-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-BaseMauiApp-
      #- name: Publish
      #  uses: chenryhabana205/publish-nuget@v8
      #  with:
      #    PROJECT_FILE_PATH: BaseMauiApp/BaseMauiApp.csproj
      #    PACKAGE_NAME: BasesMauiApp
      #    NUGET_KEY: ${{ secrets.REPO_API_KEY }}
      #    NUGET_SOURCE: https://repo.saveapis.com/repository/nuget-public/
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore BaseMauiApp/BaseMauiApp.csproj
      - name: Build
        run: dotnet build BaseMauiApp/BaseMauiApp.csproj -c Release
      - name: Pack
        run: dotnet pack BaseMauiApp/BaseMauiApp.csproj -c Release -o ./artifact --no-build
      - name: publish
        run: dotnet nuget push ./artifact/*.nupkg --source https://repo.saveapis.com/repository/nuget-public/ --api-key ${{ secrets.REPO_API_KEY }}
      #- name: Publish
      #  uses: sonatype-nexus-community/nexus-repo-github-action@master
      #  with:
      #    serverUrl: https://repo.saveapis.com/
      #    username: ${{ secrets.REPO_USERNAME }}
      #    password: ${{ secrets.REPO_PASSWORD }}
      #    format: nuget
      #    repository: nuget-public
      #    filename: ./artifact/*.nupkg