name: CD (BaseWebApi)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BaseWebApi/**
      - .github/workflows/cd_basewebapi**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Publish
        uses: chenryhabana205/publish-nuget@v1
        with:
          PROJECT_FILE_PATH: BaseWebApi/BaseWebApi.csproj
          PACKAGE_NAME: BaseWebApi
          NUGET_KEY: ${{ secrets.REPO_API_KEY }}
          NUGET_SOURCE: https://repo.saveapis.com/repository/nuget-public/
      #- name: Setup .NET Core
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: 7.0.x
      #- name: Restore
      #  if: steps.cache.outputs.cache-hit != 'true'
      #  run: dotnet restore BaseWebApi/BaseWebApi.csproj
      #- name: Build
      #  run: dotnet build BaseWebApi/BaseWebApi.csproj -c Release
      #- name: Pack
      #  run: dotnet pack BaseWebApi/BaseWebApi.csproj -c Release -o ./artifact --no-build
      #
      #- name: Publish
      #  uses: sonatype-nexus-community/nexus-repo-github-action@master
      #  with:
      #    serverUrl: https://repo.saveapis.com/
      #    username: ${{ secrets.REPO_USERNAME }}
      #    password: ${{ secrets.REPO_PASSWORD }}
      #    format: nuget
      #    repository: nuget-public
      #    filename: ./artifact/*.nupkg