name: CD (BaseMauiApp)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BaseMauiApp/**
      - .github/workflows/cd_basemauiapp**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-BaseMauiApp-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-BaseMauiApp-
      - name: Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore BaseMauiApp/BaseMauiApp.csproj
      - name: Build
        run: dotnet build BaseMauiApp/BaseMauiApp.csproj -c Release
      - name: Pack
        run: dotnet pack BaseMauiApp/BaseMauiApp.csproj -c Release -o ./artifact --no-build
      - name: List
        run: dir artifact
      - name: Publish
        run: dotnet nuget push artifact/**.nupkg --source https://repo.saveapis.com/repository/nuget-public/ --api-key ${{ secrets.REPO_API_KEY }}