name: CI (BaseWebApi)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - main
    paths:
      - BaseWebApi/**
      - .github/workflows/ci_basewebapi**
  push:
    branches:
      - development
    paths:
      - BaseWebApi/**
      - .github/workflows/ci_basewebapi**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-BaseWebApi-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-BaseWebApi-
      - name: Restore project
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore BaseWebApi/BaseWebApi.csproj
      - name: Build project (${{ matrix.config }})
        run: dotnet build BaseWebApi/BaseWebApi.csproj --configuration ${{ matrix.config }}