name: CI (BaseMauiApp)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - main
    paths:
      - BaseMauiApp/**
      - .github/workflows/ci_basemauiapp**
  push:
    branches:
      - development
    paths:
      - BaseMauiApp/**
      - .github/workflows/ci_basemauiapp**

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-BaseMauiApp-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-BaseMauiApp-
      #- name: Install Workloads
      #  if: steps.cache.outputs.cache-hit != 'true'
      #  run: dotnet workload install maui-tizen android
      - name: Restore project
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore BaseMauiApp/BaseMauiApp.csproj
      - name: Build project (${{ matrix.config }})
        run: dotnet build BaseMauiApp/BaseMauiApp.csproj --configuration ${{ matrix.config }}